### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by hitgo00** [hitgo00/2-Foodpedia#28]

**Comment by hitgo00** [comment]
SRS (Make sure that your document is complete, consistent, correct and unambiguous) - Functional/Non-Functional Requirements, Use Cases and User Stories

**Comment by hitgo00** [comment]
MoMs too

**Comment by Dare101** [comment]
Done.
[srs 2.docx](https://github.com/hitgo00/2-Foodpedia/files/6432876/srs.2.docx)
